sonarqube:
  image: sonarqube:5.6-alpine
  ports:
   - "9000:9000"
  volumes_from:
   - plugins
  restart: always 

plugins:
  image: sonarqube:5.6-alpine
  volumes:
   - /opt/sonarqube/extensions
   - /opt/sonarqube/lib/bundled-plugins
  command: /bin/true

install_plugins:
  build: plugins
  volumes_from:
   - plugins
  restart: never
